<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.33" />
        <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.2.27" />
		<PackageReference Include="AutoFixture.Xunit2" Version="4.18.1" />
		<PackageReference Include="FluentAssertions" Version="8.9.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\SnsTestReceiver.Sdk\SnsTestReceiver.Sdk.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.tests.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
