# Dependabot configuration

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - "*"

security-updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security-actions:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security-dependencies:
        patterns:
          - "*"