version: "3.8"

services:
  localstack:
    image: localstack/localstack:3
    networks:
      - test-network
    container_name: localstack
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - "./local/localstack-api:/etc/localstack/init/ready.d"
    ports:
      - "4566:4566"

networks:
  test-network:
    name: test-network
