version: "3.8"

services:
  localstack:
    image: localstack/localstack:3
    networks:
      - test-network
    container_name: localstack
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - "./local/localstack-sdk:/etc/localstack/init/ready.d"
    ports:
      - "4566:4566"

  sns-test-receiver:
    build:
      context: .
      dockerfile: ./src/SnsTestReceiver.Api/Dockerfile
    networks:
      - test-network
    container_name: sns-test-receiver
    environment:
      - SQS__Urls__0=
    depends_on:
      - localstack
    ports:
      - "5000:5000"

networks:
  test-network:
    name: test-network
