services:
  localstack:
    image: localstack/localstack:3
    container_name: localstack
    depends_on:
      - sns-test-receiver
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - "./:/etc/localstack/init/ready.d"
    ports:
      - "4566:4566"

  sns-test-receiver:
    image: ignassakalauskas/sns-test-receiver:latest
    container_name: sns-test-receiver
    ports:
      - "5000:5000"
