version: "3.8"

services:
  localstack:
    image: localstack/localstack:0.12.11
    container_name: localstack
    depends_on:
      - sns-test-receiver
    environment:
      - SERVICES=sns
      - HOSTNAME=localstack
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=XX
      - AWS_SECRET_ACCESS_KEY=XX
    volumes:
      - "./:/docker-entrypoint-initaws.d"
    ports:
      - "4566:4566"

  sns-test-receiver:
    image: ignassakalauskas/sns-test-receiver:latest
    container_name: sns-test-receiver
    ports:
      - "5000:5000"
